# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10njhyUUeC1L7H-mik2w5AEt75lEk_X0d
"""

!nvidia-smi

!pip install ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="2elmKEDa1zJdLo1Du619")
project = rf.workspace("data-trrml").project("cup-detection-v2-wj8vv")
version = project.version(2)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt source={dataset.location}/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob('/content/runs/detect/predict/*.jpg'):
    display(Image(filename=image_path, width=600))
    print("\n")